name: accumulate
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: Accumulate
  source-dirs: src
  ghc-options: 
  - -Wall 
  - -Wunused-matches
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - accumulate
      - hspec
